name: Restart Bot

on:
  push:
    branches: 
      - master

jobs:
  restart:
    name: Restart
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH command
        uses: garygrossgarten/github-action-ssh@release
        with:
          username: root
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{ secrets.PASSPHRASE }}
          command: cd ../var/www/html && bash push
